version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "agepred-serverless"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true

parameter_overrides = [
  "BucketPrefix=agepred",
  "FunctionMemorySize=2048",
  "FunctionTimeout=60",
  "PresignExpireSeconds=600",
  "ResultUrlExpireSeconds=3600",
  "CorsAllowOrigin=*",
  "CreateCloudFront=true"
]
