branch-defaults:
  main:
    environment: age-prediction-env
  single_instance_app:
    environment: age-prediction-env
global:
  application_name: age-prediction-singleinstance
  default_platform: 64bit Amazon Linux 2023 running Docker
  default_region: us-east-2
  profile: default
